version: '3.8'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TallerMecanico
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    networks:
      - mynetwork
    command: --bind-address=0.0.0.0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

networks:
  mynetwork:
