# Materia: Ingeniería de Software I 
# Maestro: González Zamora Pedro 

# Integrantes del equipo: 
# - Cárdenas Rosas Sofía 
# - Figueroa Hernández Sofia Belem 
# - López Cerecer Angélica Guadalupe 
# - Matus Valencia Elda Berenice 
# - Vega Gutiérrez Marian Eugenia

version: '3.8'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TallerMecanico
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    networks:
      - mynetwork
    command: --bind-address=0.0.0.0
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  mynetwork:
